### ISSUE TITLE
Duplicate Cache-Control header

### ISSUE THREAD

**Issue by joprice** [for-GET/know-your-http-well#38]
```bash
$ grep '"header"' json/headers.json | sort | uniq -c | sort -n | grep -v 1
   2         "header": "Cache-Control",
```

**Comment by andreineculau** [comment]
mmm, it's because `headers.md` (the source of `json/headers.json`) defines headers as request and response headers, and `Cache-Control` has semantics for both request and response..

I will leave the issue open, but probably not going to fix this myself anytime soon. Welcome to PR for the `generator` branch.

**Comment by andreineculau** [comment]
should be fine now. let me know otherwise
